image: node:6.10.0

stages:
  - validate
  - publish
  - package

# Create package artifact
package:
  stage: package
  only:
    # Should really be on every commit, but gitlab doesn't yet allow for good heuristic to keep file size reasonable
    - tags
    # Only create artifacts for main branches
    - master
    - /versions/(0|[1-9]\d*)\.(0|[1-9]\d*)/master$/
  script:
    - npm pack
  artifacts:
    name: "Package-$CI_COMMIT_REF_NAME"
    paths:
    - com.unity.immediate-window-*.tgz
    expire_in: 1 year

# Validate publish
validate:
  stage: validate
  only:
    # Only semantic version tags will be published
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
  script:
    - PACKAGE_VERSION=`cat package.json | python -c "import sys, json; print json.load(sys.stdin)['version']"`
    - ([ $CI_COMMIT_TAG == "v$PACKAGE_VERSION" ] && echo Success || exit 1)

# Publish to bintray staging
publish:
  stage: publish
  only:
    # Only semantic version tags will be published
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
  script:
    - curl -u $USER_NAME:$API_KEY https://staging-packages.unity.com/auth > .npmrc
    - npm publish
